### ISSUE TITLE
use simple-sha instead of crypto

### ISSUE THREAD

**Issue by jimmywarting** [RangerMauve/mutable-webtorrent#1]
crypto in browser don't work well
webtorrent uses simple-sha so should you

**Comment by RangerMauve** [comment]
Will do, thanks for the info. :D

One thing to note is that mutable-webtorrent doesn't work in the browser because there's currently no access to the DHT in browser clients.

As per [this issue](https://github.com/webtorrent/webtorrent-hybrid/issues/92) I want to eventually turn hybrid clients into proxies for the DHT so that a web clients will be able to look up mutable torrents.

**Comment by RangerMauve** [comment]
It should also use a pure JS version of ed25519

**Comment by jimmywarting** [comment]
also use the async version as well.

**Comment by RangerMauve** [comment]
Did this as part over mutable-webtorrent@1.3.0! Also replaced ed25519-supercop with sodium-universal which has a pure JS/WASM version for browsers. 😁
